# Hydra configuration (train.yaml)

# -----------------------------------------------------------------------------

# Each key mirrors a CLI argument from the original argparse script.

# Commented choices / defaults replicate argparse behaviour.

# -----------------------------------------------------------------------------

# Dataset & paths

# ---------------
defaults:
    - _self_
    - model_config: medium
    - neps: lstm

seed: 42
dataset: ag_news       # choices: [ag_news, imdb, amazon, dbpedia, yelp]
output_path: ./results2/      # if null ➜ "./results/dataset=${dataset}/seed=${seed}"
load_path: null        # resume checkpoint
data_path: 'data'        # if null ➜ "./.data"
val_size: 0.1

# Training approach

approach: lstm  # choices: [tfidf, lstm, transformer]

# Data & training hyper‑params

vocab_size: 20000
token_length: 128
epochs: 20
batch_size: 256
lr: 0.001
weight_decay: 0.0
data_fraction: 0.01     # (0, 1]

# Model‑specific settings

lstm_emb_dim: 64          # lstm_emb_dim
lstm_hidden_dim: 64       # lstm_hidden_dim

ffnn_hidden_layer_dim: 64

# Multi‑task learning

is_mtl: true
