pipeline_space:
  bert_lr:
    choices: [5e-5, 4e-5, 3e-5]
  batch_size: 
    choices: [16, 32, 64]
  num_bert_layers_to_unfreeze: 
    choices: [1, 2]

  data_fraction:
    lower: 0.1
    upper: 1.0
    is_fidelity: True

optimizer: "asha"
max_evaluations_total: 50
root_directory: neps_results/
