pipeline_space:
  bert_lr:
    choices: [0.00005, 0.00004, 0.00003]
  batch_size: 
    choices: [16, 32, 64]
  num_bert_layers_to_unfreeze: 
    choices: [1, 2]

  data_fraction:
    lower: 0.3
    upper: 1.0
    is_fidelity: True

optimizer: "hyperband"
max_evaluations_total: 50
root_directory: neps_results/
